//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DACDIEMBANTHAN
    {
        public string MaSinhVien { get; set; }
        public Nullable<int> TinhTrangHonNhan { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public Nullable<int> NhomMau { get; set; }
        public Nullable<int> ThanhPhanXuatThan { get; set; }
        public Nullable<int> DienUuTienGiaDinh { get; set; }
        public Nullable<int> DienUuTienBanThan { get; set; }
        public Nullable<System.DateTime> NgayVaoDoan { get; set; }
        public string NoiKetNapDoan { get; set; }
        public Nullable<System.DateTime> NgayVaoDang { get; set; }
        public string NoiKetNapDang { get; set; }
        public Nullable<System.DateTime> NgayChinhThucVaoDang { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
