//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYTHEOHOC
    {
        public string MaSinhVien { get; set; }
        public string MaLopHocPhan { get; set; }
        public int LanHoc { get; set; }
        public System.DateTime ThoiDiemDangKy { get; set; }
        public Nullable<int> HinhThucDangKy { get; set; }
        public Nullable<bool> TinhTichLuyTinChi { get; set; }
        public bool TrangThaiXuLy { get; set; }
        public Nullable<System.DateTime> ThoiDiemXuLy { get; set; }
    
        public virtual LOPHOCPHAN LOPHOCPHAN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
