//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCPHAN
    {
        public int MaSoHocPhan { get; set; }
        public string MaHocPhan { get; set; }
        public string TenHocPhan { get; set; }
        public int SoTinChi { get; set; }
        public Nullable<int> MaLoaiHocPhan { get; set; }
        public Nullable<int> MaTrinhDoDaoTao { get; set; }
        public Nullable<int> DonViPhuTrach { get; set; }
        public int SoSVToiThieu { get; set; }
        public int SoSVToiDa { get; set; }
        public Nullable<int> SoGioLyThuyet { get; set; }
        public Nullable<int> SoGioThucHanh { get; set; }
        public Nullable<int> SoGioBaiTap { get; set; }
        public Nullable<int> SoGioThaoLuan { get; set; }
        public Nullable<int> SoGioThucTap { get; set; }
        public Nullable<int> SoGioTuHoc { get; set; }
    }
}
