//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUBANTHAN
    {
        public string MaSinhVien { get; set; }
        public Nullable<int> NamTotNghiepTHPT { get; set; }
        public string XepLoaiTotNghiepTHPT { get; set; }
        public string NoiTotNghiepTHPT { get; set; }
        public string XepLoaiHocTap10 { get; set; }
        public string XepLoaiHocTap11 { get; set; }
        public string XepLoaiHocTap12 { get; set; }
        public string XepLoaiHanhKiem10 { get; set; }
        public string XepLoaiHanhKiem11 { get; set; }
        public string XepLoaiHanhKiem12 { get; set; }
        public string TenLucLuongVuTrang { get; set; }
        public Nullable<System.DateTime> NgayBatDauLLVT { get; set; }
        public Nullable<System.DateTime> NgayKetThucLLVT { get; set; }
        public string QuanHamLLVT { get; set; }
        public string NoiCongTacLLVT { get; set; }
    
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
