//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOCPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPHOCPHAN()
        {
            this.LICHHOCs = new HashSet<LICHHOC>();
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
            this.DANGKYTHEOHOCs = new HashSet<DANGKYTHEOHOC>();
        }
    
        public string TenLopHocPhan { get; set; }
        public string MaLopHocPhan { get; set; }
        public int HocKy { get; set; }
        public string MaHocPhan { get; set; }
        public int SoThuTuLop { get; set; }
        public int GiangVienPhuTrach { get; set; }
        public System.DateTime NgayHetHanDangKy { get; set; }
        public System.DateTime NgayBatDauHoc { get; set; }
        public System.DateTime NgayKetThucHoc { get; set; }
        public Nullable<int> HinhThucHoc { get; set; }
        public Nullable<int> TrangThaiHoatDong { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHOC> LICHHOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKYTHEOHOC> DANGKYTHEOHOCs { get; set; }
    }
}
