//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIGUI
    {
        public int MaNguoiGui { get; set; }
        public string HoTenNguoiGui { get; set; }
        public int TrangThai { get; set; }
        public int MaTinNhan { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TINNHAN TINNHAN { get; set; }
    }
}
