//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOINHAN
    {
        public int MaTinNhan { get; set; }
        public string MaNguoiNhan { get; set; }
        public Nullable<System.DateTime> ThoiDiemXem { get; set; }
        public string HoTen { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        public virtual TINNHAN TINNHAN { get; set; }
    }
}
