//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class THONGBAO
    {
        public int MaThongBao { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> ThoiGianDang { get; set; }
        public string NoiDung { get; set; }
    }
}
