//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINLIENHE
    {
        public string MaSinhVien { get; set; }
        public string DienThoai { get; set; }
        public string DiDong { get; set; }
        public string Email { get; set; }
        public Nullable<int> HinhThucCuTru { get; set; }
        public Nullable<int> KyTucXa { get; set; }
        public Nullable<int> QuocGia { get; set; }
        public Nullable<int> ThanhPho { get; set; }
        public Nullable<int> QuanHuyen { get; set; }
        public Nullable<int> PhuongXa { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayBatDauCuTru { get; set; }
    
        public virtual PHUONGXA PHUONGXA1 { get; set; }
        public virtual QUANHUYEN QUANHUYEN1 { get; set; }
        public virtual QUOCGIA QUOCGIA1 { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
        public virtual THANHPHO THANHPHO1 { get; set; }
        public virtual KYTUCXA KYTUCXA1 { get; set; }
    }
}
