//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TINNHAN()
        {
            this.NGUOINHANs = new HashSet<NGUOINHAN>();
        }
    
        public int MaTinNhan { get; set; }
        public string MaNguoiGui { get; set; }
        public System.DateTime ThoiDiemGui { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string HoTenNguoiGui { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOINHAN> NGUOINHANs { get; set; }
    }
}
