//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VThongTinLienHe
    {
        public string MaSinhVien { get; set; }
        public string DienThoai { get; set; }
        public string DiDong { get; set; }
        public string Email { get; set; }
        public Nullable<int> HinhThucCuTru { get; set; }
        public string TenKyTucXa { get; set; }
        public string TenQuocGia { get; set; }
        public string TenThanhPho { get; set; }
        public string TenQuanHuyen { get; set; }
        public string TenPhuongXa { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayBatDauCuTru { get; set; }
    }
}
