//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VThongTinChung
    {
        public string HoTen { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TenQuocGia { get; set; }
        public string TenDanToc { get; set; }
        public string SoCMND { get; set; }
        public string NoiCap { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string TenTonGiao { get; set; }
        public string AnhDaiDien { get; set; }
        public string MaSinhVien { get; set; }
    }
}
