//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VThongTinCaNhan
    {
        public string MaSinhVien { get; set; }
        public string TenNganh { get; set; }
        public string KhoaHoc { get; set; }
        public string HoTen { get; set; }
        public string AnhDaiDien { get; set; }
    }
}
