//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VThuongTru
    {
        public string MaSinhVien { get; set; }
        public string TenQuocGia { get; set; }
        public string TenThanhPho { get; set; }
        public string TenQuanHuyen { get; set; }
        public string TenPhuongXa { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaQuocGia { get; set; }
        public Nullable<int> MaThanhPho { get; set; }
        public Nullable<int> MaQuanHuyen { get; set; }
        public Nullable<int> MaPhuongXa { get; set; }
    }
}
