//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_HUSC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTinNhanDaGui
    {
        public int MaTinNhan { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiDiemGui { get; set; }
        public string MaNguoiGui { get; set; }
        public string HoTenNguoiGui { get; set; }
        public bool DaXoa { get; set; }
    }
}
